---

# Starting LogDNA Agent
- name: Activating LogDNA Agent Service
  become: true
  become_method: sudo
  shell: "update-rc.d logdna-agent defaults"

- name: Start LogDNA agent
  become: true
  become_method: sudo
  service:
    name: logdna-agent
    enabled: true
    state: "{{ logdna_agent_service }}"
  when: (logdna_conf_key != "" and logdna_agent_service) or logdna_agent_service == "stopped"

- debug:
    msg: "LogDNA Agent has {{ logdna_agent_service }}!"
  when: (logdna_conf_key != "" and logdna_agent_service) or logdna_agent_service == "stopped"
